# Generated by Django 2.1.3 on 2019-09-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clustering', '0002_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
