from django.conf.urls import url
# from . import views_2
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

app_name = 'polls'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
    #	url(r'home.html', views.home),
    #	url(r'homepage.html', views_2.homepage),
    # url(r'predictions_3.html', views_2.prediction),
    #	url(r'list.html', views.list_2),
    url(r'infopage.html', views.infopage),
    url(r'sources.html', views.sources),
    url(r'errorpage.html', views.errorpage),
    # url(r'clustering_7.html', views.clustering_7),
    url(r'on_one_page.html', views.clustering),
    url(r'on_two_pages.html', views.clustering_step_1),
    url(r'results.html', views.clustering_step_2),
    url(r'clustering.html', views.clustering),
    url(r'clustering_step_1.html', views.clustering_step_1),
    url(r'clustering_step_2.html', views.clustering_step_2),
    url(r'clustering_no_sessions.html', views.clustering_no_sessions),
    url(r'clustering_6_part_4.html', views.clustering),
    url(r'clustering_6_part_3.html', views.clustering_step_2),
    # url(r'clustering_6_part_2_2.html', views.clustering_6_part_2_2),
    # url(r'clustering_6_part_2.html', views.clustering_6_part_2),
    url(r'clustering_6_part_1.html', views.clustering_step_1),
    url(r'clustering_6.html', views.clustering_no_sessions),
    # url(r'clustering_5.html', views.clustering_5),
    # url(r'clustering_4.html', views.clustering_4),
    # url(r'clustering_3.html', views.clustering_3),
    # url(r'clustering_2.html', views.clustering_2),
    # url(r'clustering.html', views.clustering),
    url(r'login.html', views.login_2),
    url(r'logout.html', views.logout_2),
    url(r'signup.html', views.signup),
    url(r'delete_user.html', views.delete_user),
    #	url(r'other_test.html', views.list_3),
    #	url(r'test3.html', views.list_2),
    #	url(r'^list/$', views.list_2, name='list'),
    url(r'^infopage/$', views.infopage, name='infopage'),
    url(r'^sources/$', views.sources, name='sources'),
    url(r'^errorpage/$', views.errorpage, name='errorpage'),
    # url(r'^clustering_7/$', views.clustering_7, name='clustering_7'),
    url(r'^on_one_page/$', views.clustering, name='clustering_6_part_1_3'),
    url(r'^on_two_pages/$', views.clustering_step_1, name='clustering_6_part_1_2'),
    url(r'^results/$', views.clustering_step_2, name='clustering_6_part_1_1'),
    url(r'^clustering/$', views.clustering, name='clustering'),
    url(r'^clustering_step_1/$', views.clustering_step_1, name='clustering_step_1'),
    url(r'^clustering_step_2/$', views.clustering_step_2, name='clustering_step_2'),
    url(r'^clustering_no_sessions/$', views.clustering_no_sessions, name='clustering_no_sessions'),
    url(r'^clustering_6_part_4/$', views.clustering, name='clustering_6_4'),
    url(r'^clustering_6_part_3/$', views.clustering_step_2, name='clustering_6_part_3_2'),
    # url(r'^clustering_6_part_2_2/$', views.clustering_6_part_2_2, name='clustering_6_part_2_2'),
    # url(r'^clustering_6_part_2/$', views.clustering_6_part_2, name='clustering_6_part_2'),
    url(r'^clustering_6_part_1/$', views.clustering_step_1, name='clustering_6_part_1'),
    url(r'^clustering_6/$', views.clustering_no_sessions, name='clustering_6'),
    # url(r'^clustering_5/$', views.clustering_5, name='clustering_5'),
    # url(r'^clustering_4/$', views.clustering_4, name='clustering_4'),
    # url(r'^clustering_3/$', views.clustering_3, name='clustering_3'),
    # url(r'^clustering_2/$', views.clustering_2, name='clustering_2'),
    # url(r'^clustering/$', views.clustering, name='clustering'),
    #	url(r'^other_test/$', views.list_3, name='other_test'),
    # url(r'^upload/$', views.list_2, name='imageupload')
]
urlpatterns += staticfiles_urlpatterns()
