# Generated by Django 2.1.3 on 2019-10-20 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, max_length=33)),
                ('submit_time', models.DateTimeField(editable=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'submitted'), ('FAILURE', 'failed'), ('IGNORED', 'ignored'), ('PENDING', 'pending'), ('RECEIVED', 'received'), ('RETRY', 'retry'), ('REVOKED', 'revoked'), ('STARTED', 'started'), ('SUCCESS', 'success')], max_length=9)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('ppi_json', models.FileField(upload_to='clustering/ppi/')),
                ('survival_plotly', models.FileField(upload_to='clustering/survival/')),
                ('ppi_png', models.FileField(upload_to='clustering/ppi/')),
                ('heatmap_png', models.FileField(upload_to='clustering/heatmap/')),
                ('convergence_png', models.FileField(upload_to='clustering/convergence/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
