# Generated by Django 2.1.3 on 2019-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraphForm',
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
