# Generated by Django 3.1.6 on 2021-02-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0003_job_result_csv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PpiNetworkCache',
            fields=[
                ('network_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('data_last_modified', models.DateTimeField()),
                ('network_string', models.TextField()),
            ],
        ),
    ]
