# Generated by Django 3.1.13 on 2021-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering', '0004_ppinetworkcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='netex_json',
            field=models.FileField(null=True, upload_to='clustering/netex/'),
        ),
    ]